[windows_servers]
192.168.151.14

[windows_servers:vars]
ansible_user=administrator
ansible_password=qazwsx
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
